# Generated by Django 5.0.3 on 2024-03-31 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_homework_lesson_homeworksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='Course.lesson'),
        ),
    ]
