# Generated by Django 5.0.3 on 2024-04-05 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_alter_homework_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
